version: "3.7"

services:
  dockerskeletal:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: dockerskeletal
    restart: always
    volumes:
      - ./src:/app
      - /app/vendor
    networks:
      - nginx_proxy-network

  # mariadb:
  #   image: mariadb:10.7.8
  #   restart: always
  #   container_name: mariadb
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./mariadb:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=password
  #     - MYSQL_PASSWORD=password
  #     - MYSQL_USER=user
  #     - MYSQL_DATABASE=dockerskeletal
  #   networks:
  #     - nginx_proxy-network

networks:
  nginx_proxy-network:
    external: true
